# Generated by Django 5.1.6 on 2025-02-10 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_alter_exam_model_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_db',
            name='answer',
        ),
        migrations.AddField(
            model_name='question_db',
            name='fill_blank_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question_db',
            name='multiple_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_db',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question_db',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('short', 'Short Answer')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='question_db',
            name='short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_db',
            name='single_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 13, 31, 26, 163581)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 13, 31, 26, 163574)),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionD',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
